# Fichier : codemagic.yaml (Version Corrigée)
workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      groups:
        - android-sdk
    scripts:
  - name: Build Android App
  script: |
  cd app
  ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
